import './globals.css'
import Header from '../components/Header'
import ClientProvider from '@/components/ClientProvider'
export const metadata = {
  title: 'Pokemon',
  description: 'Generated by Decole mills'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#24B4FF]/20 opacity-1 h-screen'>
        <Header />
        <div className='lg:max-w-6xl mx-auto'>
        <ClientProvider >
          {children}
          </ClientProvider>
        </div>
        </body>
    </html>
  )
}
